//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 10.0
//

using HalconDotNet;

namespace IdentifScreem_MacWrite
{
    public partial class HDevelopExport
    {
#if !NO_EXPORT_APP_MAIN
        public HDevelopExport()
        {
            // Default settings used in HDevelop 
            HOperatorSet.SetSystem("do_low_error", "false");
            action();
        }
#endif

        // Procedures 
        // Local procedures 
        public void ConnectCamera(out HTuple hv_AcqHandle)
        {
            // Initialize local and output iconic variables 

            HOperatorSet.OpenFramegrabber("GigEVision", 0, 0, 0, 0, 0, 0, "progressive",
                -1, "default", -1, "false", "default", "0007486f017b_TheImagingSourceEuropeGmbH_DMK23G2",
                0, -1, out hv_AcqHandle);
            HOperatorSet.SetFramegrabberParam(hv_AcqHandle, "ExposureTime", 2000.0);


            return;
        }

        public void DisconnectCamera(HTuple hv_AcqHandle)
        {

            // Initialize local and output iconic variables 

            HOperatorSet.CloseFramegrabber(hv_AcqHandle);

            return;
        }

        public void get_image_from_camera(out HObject ho_Image, HTuple hv_AcqHandle, HTuple hv_ImageNum)
        {

            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_Image);

            ho_Image.Dispose();
            HOperatorSet.GrabImageAsync(out ho_Image, hv_AcqHandle, -1);

            return;
        }

        public void do_inspect(HObject ho_Image, HTuple hv_BoxModelPath, out HTuple hv_outport_result)
        {



            // Local control variables 

            HTuple hv_BoxModelID, hv_BoxModelRow, hv_BoxModelColumn;
            HTuple hv_BoxModelAngle, hv_BoxModelScore, hv_Height = new HTuple();
            HTuple hv_Width = new HTuple();

            // Initialize local and output iconic variables 

            hv_outport_result = new HTuple();
            //read_image (Image, fileName)

            HOperatorSet.ReadNccModel(hv_BoxModelPath, out hv_BoxModelID);
            HOperatorSet.FindNccModel(ho_Image, hv_BoxModelID, 0, 0, 0.5, 1, 0.5, "true",
                0, out hv_BoxModelRow, out hv_BoxModelColumn, out hv_BoxModelAngle, out hv_BoxModelScore);
            if ((int)((new HTuple((new HTuple(hv_BoxModelScore.TupleLength())).TupleEqual(
                1))).TupleAnd(new HTuple(hv_BoxModelScore.TupleGreater(0.75)))) != 0)
            {
                hv_outport_result[0] = 1;
                hv_outport_result[1] = ((((hv_BoxModelRow.TupleSelect(0)) * 65535) / hv_Height)).TupleInt()
                    ;
                hv_outport_result[2] = ((((hv_BoxModelColumn.TupleSelect(0)) * 65535) / hv_Width)).TupleInt()
                    ;
            }
            else
            {
                hv_outport_result = new HTuple();
                hv_outport_result[0] = 0;
                hv_outport_result[1] = 0;
                hv_outport_result[2] = 0;
            }
            HOperatorSet.ClearNccModel(hv_BoxModelID);

            return;
        }

        public void get_image_from_file(ref HObject ho_Image, HTuple hv_filename)
        {


            // Local control variables 

            // Initialize local and output iconic variables 
            //HOperatorSet.GenEmptyObj(out ho_Image);

            ho_Image.Dispose();
            HOperatorSet.ReadImage(out ho_Image, hv_filename);
            //get_image_size (Image, Width, Height)

            return;
        }

        public void do_inspect2(HTuple hv_fileName, out HTuple hv_outport_result)
        {


            // Local iconic variables 

            HObject ho_Image, ho_Image1 = null, ho_Regions;
            HObject ho_ConnectedRegions, ho_SelectedRegions, ho_SelectedRegions1;


            // Local control variables 

            HTuple hv_Width, hv_Height, hv_Rectangularity;
            HTuple hv_Area, hv_ModelRow, hv_ModelColumn, hv_FindModelRowNum = new HTuple();
            HTuple hv_FindModelColumnNum = new HTuple();

            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_Image);
            HOperatorSet.GenEmptyObj(out ho_Image1);
            HOperatorSet.GenEmptyObj(out ho_Regions);
            HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
            HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
            HOperatorSet.GenEmptyObj(out ho_SelectedRegions1);

            hv_outport_result = new HTuple();
            ho_Image.Dispose();
            HOperatorSet.ReadImage(out ho_Image, hv_fileName);
            HOperatorSet.GetImageSize(ho_Image, out hv_Width, out hv_Height);
            ho_Regions.Dispose();
            HOperatorSet.Threshold(ho_Image1, out ho_Regions, 0, 2);
            ho_ConnectedRegions.Dispose();
            HOperatorSet.Connection(ho_Regions, out ho_ConnectedRegions);
            HOperatorSet.Rectangularity(ho_ConnectedRegions, out hv_Rectangularity);
            ho_SelectedRegions.Dispose();
            HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_SelectedRegions, "Rectangularity",
                "and", 0.8, 1);
            ho_SelectedRegions1.Dispose();
            HOperatorSet.SelectShape(ho_SelectedRegions, out ho_SelectedRegions1, "area",
                "and", 130000, 158720);
            HOperatorSet.AreaCenter(ho_SelectedRegions1, out hv_Area, out hv_ModelRow, out hv_ModelColumn);

            if ((int)(new HTuple((new HTuple(hv_Area.TupleLength())).TupleEqual(0))) != 0)
            {
                hv_outport_result = 0;
            }
            else
            {
                hv_outport_result[0] = new HTuple(hv_Area.TupleLength());
                hv_outport_result[1] = hv_Width.TupleInt();
                hv_outport_result[2] = hv_Height.TupleInt();
                for (hv_FindModelRowNum = 3; (int)hv_FindModelRowNum <= (int)((new HTuple(hv_Area.TupleLength()
                    )) + 2); hv_FindModelRowNum = (int)hv_FindModelRowNum + 1)
                {
                    hv_outport_result[hv_FindModelRowNum] = ((hv_ModelRow.TupleSelect(hv_FindModelRowNum - 3))).TupleInt()
                        ;
                }
                for (hv_FindModelColumnNum = (new HTuple(hv_Area.TupleLength())) + 3; (int)hv_FindModelColumnNum <= (int)(((new HTuple(hv_Area.TupleLength()
                    )) + (new HTuple(hv_Area.TupleLength()))) + 2); hv_FindModelColumnNum = (int)hv_FindModelColumnNum + 1)
                {
                    hv_outport_result[hv_FindModelColumnNum] = ((hv_ModelColumn.TupleSelect((hv_FindModelColumnNum - (new HTuple(hv_Area.TupleLength()
                        ))) - 3))).TupleInt();
                }
            }


            ho_Image.Dispose();
            ho_Image1.Dispose();
            ho_Regions.Dispose();
            ho_ConnectedRegions.Dispose();
            ho_SelectedRegions.Dispose();
            ho_SelectedRegions1.Dispose();

            return;
        }

        public void do_inspect1(HObject ho_Image, HTuple hv_okPath, HTuple hv_notokPath,
            HTuple hv_testingPath, HTuple hv_startingPath, out HTuple hv_outport_result)
        {



            // Local control variables 

            HTuple hv_Width, hv_Height, hv_okModelID, hv_notokModelID;
            HTuple hv_testingModelID, hv_startingModelID, hv_okModelRow;
            HTuple hv_okModelColumn, hv_okModelAngle, hv_okModelScore;
            HTuple hv_notokModelRow, hv_notokModelColumn, hv_notokModelAngle;
            HTuple hv_notokModelScore, hv_testingModelRow, hv_testingModelColumn;
            HTuple hv_testingModelAngle, hv_testingModelScore, hv_startingModelRow;
            HTuple hv_startingModelColumn, hv_startingModelAngle, hv_startingModelScore;

            // Initialize local and output iconic variables 

            hv_outport_result = new HTuple();
            //read_image (Image, fileName)
            HOperatorSet.GetImageSize(ho_Image, out hv_Width, out hv_Height);

            HOperatorSet.ReadNccModel(hv_okPath, out hv_okModelID);
            HOperatorSet.ReadNccModel(hv_notokPath, out hv_notokModelID);
            HOperatorSet.ReadNccModel(hv_testingPath, out hv_testingModelID);
            HOperatorSet.ReadNccModel(hv_startingPath, out hv_startingModelID);


            HOperatorSet.FindNccModel(ho_Image, hv_okModelID, 0, 0, 0.5, 1, 0.5, "true",
                0, out hv_okModelRow, out hv_okModelColumn, out hv_okModelAngle, out hv_okModelScore);
            HOperatorSet.FindNccModel(ho_Image, hv_notokModelID, 0, 0, 0.5, 1, 0.5, "true",
                0, out hv_notokModelRow, out hv_notokModelColumn, out hv_notokModelAngle,
                out hv_notokModelScore);
            HOperatorSet.FindNccModel(ho_Image, hv_testingModelID, 0, 0, 0.5, 1, 0.5, "true",
                0, out hv_testingModelRow, out hv_testingModelColumn, out hv_testingModelAngle,
                out hv_testingModelScore);
            HOperatorSet.FindNccModel(ho_Image, hv_startingModelID, 0, 0, 0.5, 1, 0.5, "true",
                0, out hv_startingModelRow, out hv_startingModelColumn, out hv_startingModelAngle,
                out hv_startingModelScore);


            if ((int)((new HTuple((new HTuple(hv_okModelScore.TupleLength())).TupleEqual(
                1))).TupleAnd(new HTuple(hv_okModelScore.TupleGreater(0.75)))) != 0)
            {
                hv_outport_result[0] = 2;
            }
            else if ((int)((new HTuple((new HTuple(hv_notokModelScore.TupleLength()
                )).TupleEqual(1))).TupleAnd(new HTuple(hv_notokModelScore.TupleGreater(0.75)))) != 0)
            {
                hv_outport_result[0] = 3;
            }
            else if ((int)((new HTuple((new HTuple(hv_testingModelScore.TupleLength()
                )).TupleEqual(1))).TupleAnd(new HTuple(hv_testingModelScore.TupleGreater(
                0.75)))) != 0)
            {
                hv_outport_result[0] = 1;
            }
            else if ((int)((new HTuple((new HTuple(hv_startingModelScore.TupleLength()
                )).TupleEqual(1))).TupleAnd(new HTuple(hv_startingModelScore.TupleGreater(
                0.75)))) != 0)
            {
                hv_outport_result[0] = 0;
            }
            else
            {
                hv_outport_result[0] = 1;
            }



            HOperatorSet.ClearNccModel(hv_okModelID);
            HOperatorSet.ClearNccModel(hv_notokModelID);
            HOperatorSet.ClearNccModel(hv_testingModelID);
            HOperatorSet.ClearNccModel(hv_startingModelID);

            return;
        }

        public void get_image_resolution(HObject ho_Image, out HTuple hv_out_resolution)
        {

            // Initialize local and output iconic variables 

            hv_out_resolution = new HTuple();

            return;
        }

        // Main procedure 
        private void action()
        {

            // Local iconic variables 


            // Local control variables 

            // Initialize local and output iconic variables 



            //get_image_from_file (Image, 'C:/Users/shen/Desktop/model/success.bmp')
            //do_inspect1 (Image, 'C:/Users/shen/Desktop/model/rightResult.ncm', 'C:/Users/shen/Desktop/model/testover.ncm', testingPath, startingPath, outport_result)




            return;

        }


    }
#if !NO_EXPORT_APP_MAIN
    public class HDevelopExportApp
    {
        //static void Main(string[] args)
        //{
        //  new HDevelopExport();
        //}
    }
#endif
}

